### ISSUE TITLE
Questions regarding this game engine

### ISSUE THREAD

**Issue by Joe23232** [CleanCut/rusty_engine#18]
Hey mate, this game engine so far looks very interesting and I am considering using it over Bevy to make my game. I kinda don't like Bevy's approach as it "locks" you into a framework whereas your game engine doesn't.

I have some questions regarding this game engine though:
1. Does it support 3D, if not will it support 3D in the near future?
2. BevyUI will come out and according to the devs you will be able to make normal GUI applications, would this game engine support BevyUI as well (as this game engine is based on BevyUI)?
3. Does it do multi-threading like Bevy?
4. If a full GUI game editor comes out for Bevy, would this game engine support it (or will support it)?
5. Can I please directly chat with you on Discord (as I know you have a Discord account)?
6. What can Bevy do but this game engine can't?
7. Does this game engine aim to become as powerful as Bevy in the near future?

**Comment by CleanCut** [comment]
@Joe23232 🤔 Given that Rusty Engine is a simplification layer over Bevy, Rusty Engine is _probably_ not what you are looking for, since it is intended as a sort of training-wheels game engine for my students who are just learning Rust.  Nevertheless, I'm happy to answer your questions!


> * Does it support 3D, if not will it support 3D in the near future?

No. Rusty Engine completely hides the 3D capabilities of Bevy, and I explicitly plan to keep Rusty Engine 2D for simplicity's sake. 2D is plenty for my students to deal with while learning Rust.

> * BevyUI will come out and according to the devs you will be able to make normal GUI applications, would this game engine support BevyUI as well (as this game engine is based on BevyUI)?

I don't know! I'll have to evaluate it once it is ready and see if it makes sense to include in Rusty Engine.

> * Does it do multi-threading like Bevy?

Yes, because Rusty Engine just calls into Bevy.

> * If a full GUI game editor comes out for Bevy, would this game engine support it (or will support it)?

🤔 I anticipate that covering up a Bevy Editor with a simplification layer would be more difficult through an interface designed to expose all of Bevy's capabilities, so _probably_ not, but once again I'll have to take a look at it when it comes out and see. If there's some easy way to toggle off all the stuff I want to hide...maybe?

> * Can I please directly chat with you on Discord (as I know you have a Discord account)?

Sure! I'm `CleanCut` in the Bevy discord.

> * What can Bevy do but this game engine can't?

Lots. Bevy is way more flexible. Higher performance. All the 3D stuff. All the plugins.

It might make more sense to ask "Why would I choose Rusty Engine over Bevy?", with the answers being:

- If you only know a little Rust, mainly the bits taught in Ultimate Rust Crash Course and Ultimate Rust 2: Intermediate Concepts, and don't want to learn any more Rust.
- If you don't really want to learn about game engine concepts like entities, components, systems, and other Bevy-specific concepts.
- If you want the absolute quickest way to get something working with batteries included, and you're not fussy about the fact that there's only a limited set of features and performance is a bit lower.

If ☝🏻 that doesn't describe you, you're probably ready for Bevy.  If it _does_, then Rusty Engine is a great choice!

> * Does this game engine aim to become as powerful as Bevy in the near future?

No, definitely not. This game engine exists to be used by my students. I do intend to [continue improving Rusty Engines in ways that will make it good to make little 2D prototype games with a limited set of features](https://github.com/CleanCut/rusty_engine/issues/16). But if you want to get beyond whatever Rusty Engine provides, you'll need to switch to Bevy proper.

I see Rusty Engine as a gateway game engine for students to use until they are ready for Bevy.
